default:
  _target_: omics_rpz.models.LGBMRegressor
  n_estimators: 300
  subsample_for_bin: 400000
  subsample: 1
  num_leaves: 31
  min_split_gain: 0
  min_child_weight: 0.01
  min_child_samples: 5
  max_depth: 100
  learning_rate: 0.1
  reg_lambda: 10
  reg_alpha: 5
  colsample_bytree: 0.8
  ensemble:
  n_jobs: -1

# For 1300 DepOI
GeneEssentiality:
  _target_: omics_rpz.models.LGBMRegressor
  subsample_for_bin: 400000
  num_leaves: 4000
  min_split_gain: 0
  min_child_weight: 0.01
  min_child_samples: 5
  max_depth: 20
  learning_rate: 0.01
  reg_lambda: 0
  reg_alpha: 1
  colsample_bytree: 0.8
  n_estimators: 500
  subsample: 1

# We could easily gain some performances by increasing the n_estimators.
