repos:
- repo: local
  hooks:
    - id: docformatter
      name: Format docstrings with `docformatter`
      language: system
      types: [python]
      require_serial: true
      entry: poetry run docformatter
      args: [
        --in-place, --wrap-summaries=88, --wrap-descriptions=87, --recursive
      ]
      files: ^(omics_rpz|tests|tools)/
-   repo: local
    hooks:
    - id: isort
      name: Sorting imports with `isort`
      language: system
      types: [python]
      require_serial: true
      entry: poetry run isort
      files: ^(omics_rpz|tests|tools)/
-   repo: local
    hooks:
    - id: black
      name: Formatting files with `black`
      language: system
      types: [python]
      require_serial: true
      entry: poetry run black
      args: [
        --preview,
      ]
      files: ^(omics_rpz|tests|tools)/
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
      name: Trim trailing whitespace
    - id: end-of-file-fixer
      name: Fix end of files
      exclude: \.ipynb$
-   repo: local
    hooks:
    - id: flake8
      name: Test linting with `flake8`
      language: system
      types: [python]
      require_serial: true
      entry: poetry run flake8
      files: ^(omics_rpz|tests|tools)/
- repo: local
  hooks:
    - id: pylint
      name: Test linting with `pylint`
      language: system
      types: [python]
      require_serial: true
      entry: poetry run pylint
      args: [
        "--rcfile=.pylintrc",
      ]
      files: ^(omics_rpz|tests|tools)/
# -   repo: local
#     hooks:
#     - id: mypy
#       name: Test typing with `mypy`
#       language: system
#       types: [python]
#       require_serial: true
#       entry: poetry run mypy
#       files: ^omics_rpz/
-  repo: local
   hooks:
    - id: jupyter-nb-clear-output
      name: Clear Jupyter notebook outputs
      files: \.ipynb$
      language: system
      entry: poetry run jupyter nbconvert
      args: [
        --ClearOutputPreprocessor.enabled=True, --inplace
      ]
