default:
  _target_: omics_rpz.transforms.AutoEncoder
  repr_dim: 128
  hidden_n_layers: 1
  hidden_n_units_first: 512
  hidden_decrease_rate: 0.5
  dropout: 0.0
  bias: True
  num_epochs: 100
  batch_size: 256
  learning_rate: 0.0005
  device: cuda
  ensemble:
  early_stopping_use: True
  max_num_epochs: 300
  early_stopping_split: 0.2
  early_stopping_patience: 50
  early_stopping_delta: 0.001

TCGAPredictionTask:
  num_epochs: 100
  OS:
    repr_dim: 64
    dropout: 0
    num_epochs: 100
    batch_size: 256
    hidden_n_layers: 2
    hidden_n_units_first: 256
    hidden_decrease_rate: 0.5
    learning_rate: 0.0005

  PFS:
    repr_dim: 64
    dropout: 0
    num_epochs: 100
    batch_size: 256
    hidden_n_layers: 2
    hidden_n_units_first: 256
    hidden_decrease_rate: 0.5
    learning_rate: 0.0005

  gender:
    repr_dim: 256
    hidden_n_layers: 1
    hidden_n_units_first: 512
    dropout: 0
    num_epochs: 100
    batch_size: 128
    learning_rate: 0.0005


GeneEssentiality:
  _target_: omics_rpz.transforms.AutoEncoder
  repr_dim: 128
  hidden_n_layers: 1
  hidden_n_units_first: 256
  dropout: 0
  bias: True
  num_epochs: 100
  batch_size: 1024
  learning_rate: 0.0005
  device: cuda

ConsensusClusteringBRCA:
  repr_dim: 64
  early_stopping_use: False
