default:
  _target_: omics_rpz.transforms.MaskedAutoencoder
  repr_dim: 64
  hidden_n_layers: 2
  hidden_n_units_first: 512
  hidden_decrease_rate: 0.5
  dropout: 0.1
  bias: True
  num_epochs: 50
  batch_size: 32
  learning_rate: 0.0005
  early_stopping_use: True
  max_num_epochs: 300
  early_stopping_split: 0.2
  early_stopping_patience: 50
  early_stopping_delta: 0.001
  device: cuda
  corruption_proba: 0.3
  alpha: 1.0
  beta: 1.0
  compute_reconstruction_masked: False
  compute_reconstruction: True
  predict_mask: False
  use_vime_mask: False
  use_noise_mask: False
  use_full_noise_mask: False
  ensemble:

TCGAPredictionTask:
  num_epochs: 300
  OS:
    repr_dim: 64
    dropout: 0
    num_epochs: 100
    batch_size: 256
    hidden_n_layers: 2
    hidden_n_units_first: 256
    hidden_decrease_rate: 0.5
    learning_rate: 0.0005

  PFS:
    repr_dim: 64
    dropout: 0
    num_epochs: 100
    batch_size: 256
    hidden_n_layers: 2
    hidden_n_units_first: 256
    hidden_decrease_rate: 0.5
    learning_rate: 0.0005

  gender:
    repr_dim: 256
    hidden_n_layers: 1
    hidden_n_units_first: 512
    dropout: 0
    num_epochs: 100
    batch_size: 128
    learning_rate: 0.0005

GeneEssentiality:
  _target_:  omics_rpz.transforms.MaskedAutoencoder
  repr_dim: 128
  hidden_n_layers: 1
  hidden_n_units_first: 256
  dropout: 0
  bias: True
  num_epochs: 100
  batch_size: 1024
  learning_rate: 0.0005
  device: cuda
